name: new Game

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip wget
        pip install buildozer cython

    - name: Install Android SDK & NDK
      run: |
        sudo apt-get install -y git zip unzip openjdk-17-jdk
        sudo apt-get install -y python3-pip python3-setuptools
        pip install --upgrade Cython virtualenv

    - name: Build APK
      run: |
        pip install buildozer
        buildozer init
        sed -i 's/package.name = myapp/package.name = dungeonrpg/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.github.username/' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: dungeon-rpg-apk
        path: bin/*.apk
